/*---------------------------------------------------------------------------
;
; 	FILE NAME  	: TP2_Lib_Timers_UART.H
; 	TARGET MCUs	: C8051F020, 
; 	DESCRIPTION	: Configuration pour le TP BSE
;
; 	REVISION 1.0
;
;---------------------------------------------------------------------------*/

#ifndef __TP6_BSE_Lib_TimeBase__
#define __TP6_BSE_Lib_TimeBase__

void Config_Timer2_TimeBase(void);
void Gestion_LED(void);


#endif